### ISSUE TITLE
Suggestion:  Add Poplar to Fill Type for Load Course

### ISSUE THREAD

**Issue by proactivepcc** [Stephan-S/FS25_AutoDrive#133]
I setup my planter on a course and had it set to the load option and put a waypoint next to my trailer with pallets of poplar but could not get it to refill the planter.  Not a big deal to do it manually but just a nice wishlist item.``

**Comment by Iwan1803** [comment]
A screenshot of the situation an dloading point could be helpful.

**Comment by proactivepcc** [comment]
![Image](https://github.com/user-attachments/assets/e18cc029-8bf3-48ba-9f27-2f7635ac5f17)

The fill type option for the PL-75 tree planter is completely empty.

**Comment by Iwan1803** [comment]
You cannot and do not need to select pallets. Incidentally, I don't believe that pallets fixed with tension belts are recognized as cargo.

**Comment by proactivepcc** [comment]
Not sure on how to load poplar without pallets, if I'm missing a way please let me know.  I was able to manually load them with tension belts on but I also tried with tension belts off and still not recognized, only able to manually load the poplar into the planter.

**Comment by ThomasMatern** [comment]
We already had special rules for seeders, sprayers and salt-spreaders - and I have added tree-planters to this. They will load from pallets.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS25_AutoDrive/releases/tag/3.0.0.6
