### ISSUE TITLE
node height issue with creating turns with mouse and scrolling

### ISSUE THREAD

**Issue by gabrieltackitt** [Stephan-S/FS25_AutoDrive#49]
When creating curves and turns using the mouse and scroll wheel, sometimes nodes end up buried into terrain and not sitting on ground like the normal behavior.

**Comment by fudoido** [comment]
noticed the opposite happening also, getting lifted instead of buried, but this behaviour is happening when something is in the way, vehicle or implement, as if autodrive detects the height of the object as a "level" instead of considering the ground level.

**Comment by ThomasMatern** [comment]
@fudoido it's the same problem - AD took the elevation from the start node and applied it to all points on the curve. Depending on the terrain, this meant that the nodes were either floating or dropping into the ground. This has been fixed - the node height is now calculated for each node.

**Comment by Iwan1803** [comment]
-> https://github.com/Stephan-S/FS25_AutoDrive/releases/tag/3.0.0.2
If problem still exists with the new version, then please open a new issue.
